---
- hosts: all
  sudo: yes
  tasks:
    - name: install unzip
      apt: name=unzip update_cache=yes

    - name: install consul
      shell: wget https://releases.hashicorp.com/consul/0.4.1/consul_0.4.1_linux_amd64.zip
          && unzip consul_0.4.1_linux_amd64.zip
          && mv consul /usr/local/bin
          && rm consul_0.4.1_linux_amd64.zip creates=/usr/local/bin/consul

    - name: install consul-template
      shell: wget https://releases.hashicorp.com/consul-template/0.2.0/consul-template_0.2.0_linux_amd64.zip
          && unzip consul-template_0.2.0_linux_amd64.zip
          && mv consul-template /usr/local/bin
          && rm consul-template_0.2.0_linux_amd64.zip creates=/usr/local/bin/consul-template

    - name: install registretor
      shell: wget https://github.com/gliderlabs/registrator/releases/download/v0.4.0/registrator_0.4.0_linux_x86_64.tgz
          && tar xzf registrator_0.4.0_linux_x86_64.tgz
          && mv registrator /usr/local/bin
          && rm registrator_0.4.0_linux_x86_64.tgz creates=/usr/local/bin/registrator

    - name: install haproxy
      apt: name=haproxy

    - name: setup haproxy
      command: sed -i -e 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
